import * as fs from 'fs';
import * as path from 'path';

function usage(): string {
  return `
usage:
${process.argv[1]} data-dir frequency_lists.ts

generates frequency_lists.ts (zxcvbn's ranked dictionary file) from word frequency data.
data-dir should contain frequency counts, as generated by the data-scripts/count_* scripts.

DICTIONARIES controls which frequency data will be included and at maximum how many tokens
per dictionary.

If a token appears in multiple frequency lists, it will only appear once in emitted file,
in the dictionary where it has lowest rank.

Short tokens, if rare, are also filtered out. If a token has higher rank than 10**(token.length),
it will be excluded because a bruteforce match would have given it a lower guess score.

A warning will be printed if DICTIONARIES contains a dictionary name that doesn't appear in
passed data dir, or vice-versa.
`;
}

// maps dict name to num words. null means "include all words"
// names are built separately via build_name_lists.ts and shipped as optional entry points
const DICTIONARIES: Record<string, number | null> = {
  passwords: 30000,
};

type FreqLists = Record<string, Record<string, number>>;

function parseFrequencyLists(dataDir: string): FreqLists {
  const freqLists: FreqLists = {};
  const entries = fs.readdirSync(dataDir, { withFileTypes: true });

  for (const ent of entries) {
    if (!ent.isFile()) continue;
    const filename = ent.name;
    const freqListName = path.basename(filename, path.extname(filename));
    if (!(freqListName in DICTIONARIES)) {
      console.warn(
        `Warning: ${freqListName} appears in ${dataDir} directory but not in DICTIONARY settings. Excluding.`
      );
      continue;
    }
    const tokenToRank: Record<string, number> = {};
    const content = fs.readFileSync(path.join(dataDir, filename), 'utf8');
    const lines = content.split(/\r?\n/);
    for (let i = 0; i < lines.length; i++) {
      const parts = lines[i].trim().split(/\s+/);
      if (parts.length === 0 || !parts[0]) continue;
      const token = parts[0];
      const rank = i + 1;
      tokenToRank[token] = rank;
    }
    freqLists[freqListName] = tokenToRank;
  }

  for (const freqListName of Object.keys(DICTIONARIES)) {
    if (!(freqListName in freqLists)) {
      console.warn(
        `Warning: ${freqListName} appears in DICTIONARY settings but not in ${dataDir} directory. Excluding.`
      );
    }
  }

  return freqLists;
}

function isRareAndShort(token: string, rank: number): boolean {
  return rank >= Math.pow(10, token.length);
}

function hasCommaOrDoubleQuote(token: string): boolean {
  return token.includes(',') || token.includes('"');
}

function filterFrequencyLists(freqLists: FreqLists): Record<string, string[]> {
  const filteredTokenAndRank: Record<string, [string, number][]> = {};
  const minimumRank: Record<string, number> = {};
  const minimumName: Record<string, string> = {};

  for (const name of Object.keys(freqLists)) {
    filteredTokenAndRank[name] = [];
  }

  for (const [name, tokenToRank] of Object.entries(freqLists)) {
    for (const [token, rank] of Object.entries(tokenToRank)) {
      if (!(token in minimumRank)) {
        minimumRank[token] = rank;
        minimumName[token] = name;
      } else {
        const minRank = minimumRank[token];
        if (rank < minRank) {
          minimumRank[token] = rank;
          minimumName[token] = name;
        }
      }
    }
  }

  for (const [name, tokenToRank] of Object.entries(freqLists)) {
    for (const [token, rank] of Object.entries(tokenToRank)) {
      if (minimumName[token] !== name) continue;
      if (isRareAndShort(token, rank) || hasCommaOrDoubleQuote(token)) continue;
      filteredTokenAndRank[name].push([token, rank]);
    }
  }

  const result: Record<string, string[]> = {};
  for (const [name, tokenRankPairs] of Object.entries(filteredTokenAndRank)) {
    tokenRankPairs.sort((a, b) => a[1] - b[1]);
    let list = tokenRankPairs.map((p) => p[0]);
    const cutoffLimit = DICTIONARIES[name];
    if (cutoffLimit != null && list.length > cutoffLimit) {
      list = list.slice(0, cutoffLimit);
    }
    result[name] = list;
  }
  return result;
}

function toKv(lst: string[], lstName: string): string {
  const items = lst.map((t) => JSON.stringify(t)).join(', ');
  return `${lstName}: [${items}]`;
}

function main(): void {
  if (process.argv.length !== 4) {
    console.log(usage());
    process.exit(1);
  }
  const dataDir = process.argv[2];
  const outputFile = process.argv[3];
  const unfilteredFreqLists = parseFrequencyLists(dataDir);
  const freqLists = filterFrequencyLists(unfilteredFreqLists);
  const scriptName = path.basename(process.argv[1]);
  const lines = Object.entries(freqLists).map(([name, lst]) => toKv(lst, name));
  const content = [
    `// generated by ${scriptName}`,
    'const frequency_lists = {',
    '  ' + lines.join(',\n  '),
    '}',
    'export default frequency_lists',
    '',
  ].join('\n');
  fs.writeFileSync(outputFile, content, 'utf8');
}

main();
