import * as fs from 'fs';
import * as path from 'path';

const REPO_ROOT = path.resolve(__dirname, '..');
const DATA_DIR = path.join(REPO_ROOT, 'data');
const OUT_DIR = path.join(REPO_ROOT, 'src', 'names');

const LISTS = [
  { name: 'finnish', file: path.join(DATA_DIR, 'fi', 'names.txt') },
  { name: 'english', file: path.join(DATA_DIR, 'en', 'names.txt') },
] as const;

function readNames(filePath: string): string[] {
  const content = fs.readFileSync(filePath, 'utf8');
  return content
    .split(/\r?\n/)
    .map((line) => line.trim().toLowerCase())
    .filter((token) => token.length > 0);
}

function writeNameModule(name: string, tokens: string[], outPath: string): void {
  const scriptName = path.basename(__filename);
  const items = tokens.map((t) => JSON.stringify(t)).join(', ');
  const content = [
    `// generated by ${scriptName}`,
    `/** Optional name list for zxcvbn (e.g. zxcvbn(password, { names: finnishNames })). */`,
    `const names: string[] = [${items}];`,
    `export default names;`,
    '',
  ].join('\n');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, content, 'utf8');
}

function main(): void {
  for (const { name, file } of LISTS) {
    if (!fs.existsSync(file)) {
      console.warn(`Warning: ${file} not found, skipping ${name}`);
      continue;
    }
    const tokens = readNames(file);
    const outPath = path.join(OUT_DIR, `${name}.ts`);
    writeNameModule(name, tokens, outPath);
    console.log(`Wrote ${outPath} (${tokens.length} names)`);
  }
}

main();
