import * as fs from 'fs';

function usage(): string {
  return `
constructs adjacency_graphs.ts from QWERTY and DVORAK keyboard layouts

usage:
${process.argv[1]} adjacency_graphs.ts
`;
}

const qwerty = `
\`~ 1! 2@ 3# 4$ 5% 6^ 7& 8* 9( 0) -_ =+
    qQ wW eE rR tT yY uU iI oO pP [{ ]} \\|
     aA sS dD fF gG hH jJ kK lL ;: '"
      zZ xX cC vV bB nN mM ,< .> /?
`;

const dvorak = `
\`~ 1! 2@ 3# 4$ 5% 6^ 7& 8* 9( 0) [{ ]}
    '" ,< .> pP yY fF gG cC rR lL /? =+ \\|
     aA oO eE uU iI dD hH tT nN sS -_
      ;: qQ jJ kK xX bB mM wW vV zZ
`;

const keypad = `
  / * -
7 8 9 +
4 5 6
1 2 3
  0 .
`;

const mac_keypad = `
  = / *
7 8 9 -
4 5 6 +
1 2 3
  0 .
`;

type Coord = { x: number; y: number };

function getSlantedAdjacentCoords(x: number, y: number): Coord[] {
  return [
    { x: x - 1, y },
    { x, y: y - 1 },
    { x: x + 1, y: y - 1 },
    { x: x + 1, y },
    { x, y: y + 1 },
    { x: x - 1, y: y + 1 },
  ];
}

function getAlignedAdjacentCoords(x: number, y: number): Coord[] {
  return [
    { x: x - 1, y },
    { x: x - 1, y: y - 1 },
    { x, y: y - 1 },
    { x: x + 1, y: y - 1 },
    { x: x + 1, y },
    { x: x + 1, y: y + 1 },
    { x, y: y + 1 },
    { x: x - 1, y: y + 1 },
  ];
}

function coordKey(c: Coord): string {
  return `${c.x},${c.y}`;
}

function buildGraph(
  layoutStr: string,
  slanted: boolean
): Record<string, (string | null)[]> {
  const positionTable: Record<string, string> = {};
  const tokens = layoutStr.split(/\s+/).filter((t) => t.length > 0);
  const tokenSize = tokens[0].length;
  const xUnit = tokenSize + 1;
  const adjacencyFunc = slanted
    ? getSlantedAdjacentCoords
    : getAlignedAdjacentCoords;

  const lines = layoutStr.split(/\n/);
  for (let y = 0; y < lines.length; y++) {
    const line = lines[y];
    const slant = slanted ? y - 1 : 0;
    const lineTokens = line.split(/\s+/).filter((t) => t.length > 0);
    for (const token of lineTokens) {
      const idx = line.indexOf(token);
      const pos = idx - slant;
      const x = Math.floor(pos / xUnit);
      const remainder = pos % xUnit;
      if (remainder !== 0) {
        throw new Error(`unexpected x offset for ${token} in:\n${layoutStr}`);
      }
      positionTable[coordKey({ x, y })] = token;
    }
  }

  const adjacencyGraph: Record<string, (string | null)[]> = {};
  for (const [key, chars] of Object.entries(positionTable)) {
    const [x, y] = key.split(',').map(Number);
    for (const char of chars) {
      adjacencyGraph[char] = [];
      for (const coord of adjacencyFunc(x, y)) {
        const k = coordKey(coord);
        adjacencyGraph[char].push(positionTable[k] ?? null);
      }
    }
  }
  return adjacencyGraph;
}

function stringifyGraph(graph: Record<string, (string | null)[]>): string {
  const sortedKeys = Object.keys(graph).sort();
  const sorted: Record<string, (string | null)[]> = {};
  for (const k of sortedKeys) {
    sorted[k] = graph[k];
  }
  return JSON.stringify(sorted);
}

function main(): void {
  if (process.argv.length !== 3) {
    console.log(usage());
    process.exit(1);
  }
  const outputFile = process.argv[2];
  const layouts: [string, string, boolean][] = [
    ['qwerty', qwerty, true],
    ['dvorak', dvorak, true],
    ['keypad', keypad, false],
    ['mac_keypad', mac_keypad, false],
  ];
  const lines = layouts.map(([name, layout, slanted]) => {
    const graph = buildGraph(layout, slanted);
    return `${name}: ${stringifyGraph(graph)}`;
  });
  const content = [
    '// generated by build_keyboard_adjacency_graphs.ts',
    'const adjacency_graphs: Record<string, Record<string, (string | null)[]>> = {',
    '  ' + lines.join(',\n  '),
    '}',
    'export default adjacency_graphs',
    '',
  ].join('\n');
  fs.writeFileSync(outputFile, content, 'utf8');
}

main();
